### ISSUE TITLE
Feature request: Autosave 

### ISSUE THREAD

**Issue by devaughnsaxa** [CollinBrennan/GenGo#1]
Good day,
It would be nice if there was a save button and autosave for the work in progress for users. So, if the browser is closed accidentally, the user don't lose everything. (Don't ask me how I know this) .

I don't mind implementing it and creating a pull request if needed.

**Comment by CollinBrennan** [comment]
> Good day, It would be nice if there was a save button and autosave for the work in progress for users. So, if the browser is closed accidentally, the user don't lose everything. (Don't ask me how I know this) .
> 
> I don't mind implementing it and creating a pull request if needed.

Hi! I apologize that you lost all your work and hope that it did not cause too much damage. I was actually just getting ready to rebuild this project from the ground up and the new version would most likely have the feature that you mention. The current version of the app was a small project that I wrote in high school to practice coding, but the code is really messy and unsustainable so hopefully a better version will come in the near future.

Thank you for using the app, I appreciate the feedback!

**Comment by devaughnsaxa** [comment]
No, it was okay. I didn't lose anything serious. No damage was taken 😃 

I'm looking forward for the new project. But this one is already really good. It works, right? That's what matters in the end.

**Comment by CollinBrennan** [comment]
The new generator is currently in development at [this repo](https://github.com/CollinBrennan/word-generator) :D

**Comment by devaughnsaxa** [comment]
Amazing, thank you
