### ISSUE TITLE
Rewrite Crashing Issue

### ISSUE THREAD

**Issue by CreatureConstruct** [CollinBrennan/GenGo#2]
Greetings and salutations,
I've discovered an issue where every time I input multiple possible characters to replace another, (ex. "ë: aë eë ië oë uë yë", or "ch: cha chi chu") the entire generator crashes. The only way I can get it working again is if I close all browser tabs linked to the GenGo generator and reopen GenGo in a new tab (which automatically discards all work).

I tried getting around the issue by rewriting the order of things a little differently, (as such: "ë: aë, ë: eë, ë: ië, ë: oë, ë: uë, ë: yë") but the generator still crashed anyway. Is there any specific way to write things in order to fix this? If not, I hope it's able to be fixed soon.

An additional minor suggestion I have would be to make the "list" option give you more word columns side by side. Maybe about four or so, instead of one. I only suggest this because it'd be easier to see more words at once.

Thanks for reading.

**Comment by CollinBrennan** [comment]
Hi! I'm so sorry for not responding to this earlier. I've been really busy with school and other life stuff but I've now found time to work on my projects.

I've been able to replicate the problem you are having and the generator does indeed crash. I wrote this program when I was first learning to code so the source itself is pretty unmanageable. I don't have a short-term fix for you right now unfortunately but I plan on releasing a rewritten version of the program in the near future. Thanks for the feedback!
