### ISSUE TITLE
Feature request: Filter clusters of character groups

### ISSUE THREAD

**Issue by Br1lli** [CollinBrennan/GenGo#3]
Hello,

I'm a conlanger and like to use this tool for generating words, but I noticed that in order to filter characters, they all have to be lowercase, so you can't filter group names. That is very impractical in terms of generating words for conlangs with complex phonological rules like e.g. vowel harmony, because you have to write down every single unwanted combination of characters, which, depending on how long the sequences are, in my case 4 characters, can take ages and space in the text bar, so filtering group names as well, so that all character of a group is filtered out, would be very useful and save a lot of time.

Yours, Brilli

**Comment by CollinBrennan** [comment]
Hi Brilli,

I apologize for the very very late response. I am currently working on the new version of the generator. I don't think I quite understand your request. Could you provide me an example of the feature you would like to see? Thank you for using my project! It means a lot to me.

Best,
Collin

**Comment by CollinBrennan** [comment]
The [new generator](https://github.com/CollinBrennan/word-generator) now supports this feature.
